
const API_URL = "https://script.google.com/macros/s/AKfycbytW-z1l2ZzhOjbgpJrknNiRb-KnwS0gE1KERnvVMux37g4YGbWgJpYuj53heuthsJi/exec";
const state = {categories:[],products:[],settings:{},activeCategory:"all",search:"",cart:JSON.parse(localStorage.getItem("dg-cart")||"{}")};
const $=s=>document.querySelector(s);
const els={categoryFilters:$("#categoryFilters"),productGrid:$("#productGrid"),catalogStatus:$("#catalogStatus"),searchInput:$("#searchInput"),cartButton:$("#cartButton"),cartCount:$("#cartCount"),cartDrawer:$("#cartDrawer"),closeCartButton:$("#closeCartButton"),drawerBackdrop:$("#drawerBackdrop"),cartItems:$("#cartItems"),cartTotal:$("#cartTotal"),checkoutButton:$("#checkoutButton"),productDialog:$("#productDialog"),productDialogContent:$("#productDialogContent"),checkoutDialog:$("#checkoutDialog"),checkoutForm:$("#checkoutForm"),checkoutStatus:$("#checkoutStatus"),pickupDate:$("#pickupDate")};
const money=v=>new Intl.NumberFormat("uk-UA",{style:"currency",currency:"UAH",maximumFractionDigits:2}).format(v);
const esc=(v="")=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function saveCart(){localStorage.setItem("dg-cart",JSON.stringify(state.cart));renderCart()}
function entries(){return Object.entries(state.cart).map(([id,quantity])=>{const product=state.products.find(p=>p.id===id);return product?{product,quantity}:null}).filter(Boolean)}
function total(){return entries().reduce((s,i)=>s+i.product.price*i.quantity,0)}
async function loadCatalog(){try{const r=await fetch(`${API_URL}?action=catalog`);const d=await r.json();if(!d.success)throw new Error(d.error||"Помилка");state.categories=d.categories||[];state.products=d.products||[];state.settings=d.settings||{};renderFilters();renderProducts();renderCart()}catch(e){els.catalogStatus.textContent="Каталог не завантажився. Перевірте доступ до Apps Script.";console.error(e)}}
function renderFilters(){els.categoryFilters.innerHTML=[`<button class="${state.activeCategory==="all"?"active":""}" data-category="all">Усі товари</button>`,...state.categories.map(c=>`<button class="${state.activeCategory===c.name?"active":""}" data-category="${esc(c.name)}">${esc(c.name)}</button>`)].join("");els.categoryFilters.querySelectorAll("button").forEach(b=>b.onclick=()=>{state.activeCategory=b.dataset.category;renderFilters();renderProducts()})}
function filtered(){const t=state.search.trim().toLowerCase();return state.products.filter(p=>(state.activeCategory==="all"||p.category===state.activeCategory)&&(!t||`${p.name} ${p.description} ${p.category}`.toLowerCase().includes(t)))}
function renderProducts(){const ps=filtered();els.catalogStatus.style.display=ps.length?"none":"block";if(!ps.length)els.catalogStatus.textContent="У цій категорії поки немає товарів.";els.productGrid.innerHTML=ps.map(p=>`<article class="product-card">${p.images&&p.images[0]?`<img loading="lazy" src="${esc(p.images[0])}" alt="${esc(p.name)}">`:`<div class="product-placeholder">${esc(p.category)}</div>`}<div class="product-card-body"><span class="badge ${p.available?"":"unavailable"}">${p.available?(p.madeToOrder?"Під замовлення":"Є в наявності"):"Тимчасово немає"}</span><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><div class="product-card-footer"><div><strong class="price">${money(p.price)}</strong><small> / ${esc(p.unit)}</small></div><button data-product="${esc(p.id)}" ${p.available?"":"disabled"}>Додати</button></div></div></article>`).join("");els.productGrid.querySelectorAll("[data-product]").forEach(b=>b.onclick=()=>add(b.dataset.product))}
function add(id){const p=state.products.find(x=>x.id===id);if(!p||!p.available)return;state.cart[id]=Number(state.cart[id]||0)+(Number(state.cart[id]||0)?Number(p.quantityStep||1):Number(p.minimumQuantity||1));saveCart();openCart()}
function change(id,dir){const p=state.products.find(x=>x.id===id);if(!p)return;const step=Number(p.quantityStep||1),min=Number(p.minimumQuantity||step),next=Number(state.cart[id]||min)+dir*step;if(next<min)delete state.cart[id];else state.cart[id]=Number(next.toFixed(3));saveCart()}
function renderCart(){const es=entries();els.cartCount.textContent=es.length;els.cartTotal.textContent=money(total());els.checkoutButton.disabled=!es.length;els.cartItems.innerHTML=es.length?es.map(i=>`<div class="cart-item"><div><h4>${esc(i.product.name)}</h4><div>${money(i.product.price)} / ${esc(i.product.unit)}</div><button class="remove-link" data-remove="${esc(i.product.id)}">Видалити</button></div><div><strong>${money(i.product.price*i.quantity)}</strong><div class="qty-controls"><button data-minus="${esc(i.product.id)}">−</button><span>${i.quantity} ${esc(i.product.unit)}</span><button data-plus="${esc(i.product.id)}">+</button></div></div></div>`).join(""):"<p>Кошик поки порожній.</p>";els.cartItems.querySelectorAll("[data-minus]").forEach(b=>b.onclick=()=>change(b.dataset.minus,-1));els.cartItems.querySelectorAll("[data-plus]").forEach(b=>b.onclick=()=>change(b.dataset.plus,1));els.cartItems.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{delete state.cart[b.dataset.remove];saveCart()})}
function openCart(){els.cartDrawer.classList.add("open");els.drawerBackdrop.classList.add("open")}
function closeCart(){els.cartDrawer.classList.remove("open");els.drawerBackdrop.classList.remove("open")}
function setDate(){const days=Math.max(1,...entries().map(i=>Number(i.product.preparationDays||0)));const d=new Date();d.setDate(d.getDate()+days);const iso=d.toISOString().slice(0,10);els.pickupDate.min=iso;els.pickupDate.value=iso}
async function submitOrder(e){e.preventDefault();const f=new FormData(els.checkoutForm);const payload={customerName:f.get("customerName"),phone:f.get("phone"),pickupDate:f.get("pickupDate"),pickupTime:f.get("pickupTime"),paymentMethod:f.get("paymentMethod"),comment:f.get("comment"),items:entries().map(i=>({productId:i.product.id,quantity:i.quantity}))};els.checkoutStatus.textContent="Надсилаємо замовлення…";try{const r=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload)});const d=await r.json();if(!d.success)throw new Error(d.error||"Помилка");els.checkoutStatus.textContent=`Замовлення ${d.orderNumber} прийнято. Сума: ${money(d.total)}.`;state.cart={};saveCart();setTimeout(()=>{els.checkoutDialog.close();closeCart();alert(`Дякуємо! Замовлення ${d.orderNumber} прийнято.`)},900)}catch(err){els.checkoutStatus.textContent=err.message}}
els.searchInput.oninput=e=>{state.search=e.target.value;renderProducts()};els.cartButton.onclick=openCart;els.closeCartButton.onclick=closeCart;els.drawerBackdrop.onclick=closeCart;els.checkoutButton.onclick=()=>{if(!entries().length)return;setDate();els.checkoutDialog.showModal()};els.checkoutForm.onsubmit=submitOrder;document.querySelectorAll("[data-close-dialog]").forEach(b=>b.onclick=()=>els.productDialog.close());document.querySelectorAll("[data-close-checkout]").forEach(b=>b.onclick=()=>els.checkoutDialog.close());
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js").catch(console.error));
loadCatalog();
